// Public expansion cases. Final answers, hidden motives and valid evidence
// edges live exclusively in the server-side Cloudflare rules registry.

export const Case_Data_Lvl_06 = {
  case_id: 'Lvl_06',
  initial_zone: 'zone_auction_floor',
  title: '午夜拍卖',
  subtitle: 'Midnight Auction',
  difficulty: 'NORMAL',
  setting: '2160年，悬浮于旧城区上空的棱镜博物馆。一场匿名拍卖结束后，鉴定师死在密封展柜旁，一件国宝级记忆雕塑被换成赝品。',
  scene: {
    description: '零点钟声刚过，棱镜博物馆切断了外部航道。首席鉴定师 Mara Ilyan 倒在密封展柜旁，防护手套内侧残留银色纳米纤维。真正的「雨中记忆」不翼而飞，而拍卖系统坚持展柜从未开启。',
    zones: {
      zone_auction_floor: { dom_id: 'area-auction-floor', label: '午夜展厅 · 案发现场', entry_requirement: null },
      zone_restoration_lab: { dom_id: 'area-restoration-lab', label: '文物修复室', entry_requirement: 'analyze_forensics' },
      zone_auction_mesh: { dom_id: 'area-auction-mesh', label: '匿名竞价网络', entry_requirement: 'hack_terminal' },
      zone_loading_spire: { dom_id: 'area-loading-spire', label: '空运装卸塔', entry_requirement: 'tail_suspect' },
    },
  },
  clue_dictionary: [
    { clue_id: 'h_01', keyword: '纳米纤维毒痕', description: 'Mara 手套内侧的银色纤维会在体温激活后释放神经毒素；纤维来自修复室的仿古封装设备。', visual_icon: '🧤', weight: 'CRITICAL' },
    { clue_id: 'h_02', keyword: '未开启的展柜', description: '展柜门锁没有动作，但底座在 00:07 进入了四十秒维护模式，足以从下方交换展品。', visual_icon: '🗿', weight: 'HIGH' },
    { clue_id: 'h_03', keyword: 'Tessa 的维护签名', description: '维护模式使用修复主管 Tessa Vale 的生物签名授权，并被伪装成例行湿度校准。', visual_icon: '🪪', weight: 'CRITICAL' },
    { clue_id: 'h_04', keyword: '赝品树脂谱', description: '赝品所用记忆树脂与修复室三周前登记的一批实验材料完全一致。', visual_icon: '🧪', weight: 'HIGH' },
    { clue_id: 'h_05', keyword: '匿名竞价回流', description: '最终中标资金经七层匿名账户回流到 Tessa 控制的离岸文物基金。', visual_icon: '💠', weight: 'CRITICAL' },
    { clue_id: 'h_06', keyword: 'Juno 巡逻记录', description: '安保档案员 Juno 的眼镜记录连续覆盖外环巡逻路线，证明她未进入展厅维护层。', visual_icon: '👓', weight: 'LOW' },
    { clue_id: 'h_07', keyword: '装卸塔冷箱', description: 'Pavel 的空运冷箱中检测到真品的量子标记，但封条显示它由博物馆内部人员提前装入。', visual_icon: '📦', weight: 'HIGH' },
    { clue_id: 'h_08', keyword: 'Mara 的鉴定备忘', description: 'Mara 在死前写下「修复批次 R-41 是复制源」，并预约次日向文化署举报。', visual_icon: '📝', weight: 'HIGH' },
    { clue_id: 'h_secret_99', keyword: '底座机械臂缓存', description: '展柜底座的离线缓存还原出交换过程：机械臂将真品送入 Tessa 标记的冷箱，随后把毒纤维压入 Mara 的手套。', visual_icon: '🦾', weight: 'CRITICAL', unlock_turn: 6 },
  ],
  npcs: [
    { npc_id: 'npc_01', name: 'Tessa Vale', role: '博物馆修复主管', public_persona: '温和克制，坚称维护模式只是保护展品的例行操作', personality: '擅长用专业术语稀释责任，被问及 R-41 批次和离岸基金时会明显加快语速', avatar: '🧑‍🎨', initial_statement: 'Mara 对修复技术一向多疑。维护记录很正常，展品也从未离开过展柜。' },
    { npc_id: 'npc_02', name: 'Juno Kade', role: '夜班安保档案员', public_persona: '纪律严谨，对系统记录比对人类证词更有信心', personality: '不喜欢管理层干涉记录，但需要看到明确的权限证据才会合作', avatar: '🛡️', initial_statement: '展厅锁没有开过，但底座维护层不归安保控制。那是修复部门的权限。' },
    { npc_id: 'npc_03', name: 'Pavel Orr', role: '私人艺术品运输商', public_persona: '圆滑世故，声称只接收已封装的合法货物', personality: '害怕失去运输执照，面对冷箱量子标记时愿意交代交接人', avatar: '🚁', initial_statement: '我的冷箱由博物馆装载，我没有打开过。你们该去问给我签放行单的人。' },
  ],
  conflict_dictionary: [{ clue_A: 'h_06', clue_B: 'h_03', reason: "Juno's continuous patrol clears her while Tessa's biometric signature authorizes the hidden maintenance path." }],
  hidden_clues: [{ clue_id: 'h_secret_99', unlock_turn: 6, text: '展柜底座报告：发现未同步的机械臂诊断缓存……' }],
  checkpoints: ['zone_auction_floor', 'zone_restoration_lab'],
  zone_clue_map: {
    zone_auction_floor: ['h_01', 'h_02', 'h_08'],
    zone_restoration_lab: ['h_03', 'h_04', 'h_secret_99'],
    zone_auction_mesh: ['h_05'],
    zone_loading_spire: ['h_06', 'h_07'],
  },
  zone_layout: {
    zone_auction_floor: { x: 50, y: 18, label: '午夜展厅', sublabel: '案发现场', icon: '🏛️', color: '#ff3860' },
    zone_restoration_lab: { x: 18, y: 60, label: '修复室', sublabel: '复制设备', icon: '🧪', color: '#00e5ff' },
    zone_auction_mesh: { x: 82, y: 60, label: '竞价网络', sublabel: '资金回流', icon: '💠', color: '#a78bfa' },
    zone_loading_spire: { x: 50, y: 85, label: '装卸塔', sublabel: '空运冷箱', icon: '🚁', color: '#ffaa00' },
  },
  zone_connections: [['zone_auction_floor', 'zone_restoration_lab'], ['zone_auction_floor', 'zone_auction_mesh'], ['zone_auction_floor', 'zone_loading_spire'], ['zone_restoration_lab', 'zone_loading_spire'], ['zone_auction_mesh', 'zone_loading_spire']],
  en: {
    title: 'Midnight Auction', subtitle: 'Case LVL-06',
    setting: '2160. The Prism Museum floats above the old city. After an anonymous auction, an appraiser dies beside a sealed display and a national memory sculpture is replaced by a forgery.',
    scene: {
      description: "Just after midnight, the Prism Museum closes its external flight lanes. Chief appraiser Mara Ilyan lies beside a sealed display, silver nanofibers inside her gloves. The real Memory in Rain is gone, while the auction system insists the case never opened.",
      zones: {
        zone_auction_floor: { dom_id: 'area-auction-floor', label: 'Midnight Gallery · Crime Scene', entry_requirement: null },
        zone_restoration_lab: { dom_id: 'area-restoration-lab', label: 'Artifact Restoration Lab', entry_requirement: 'analyze_forensics' },
        zone_auction_mesh: { dom_id: 'area-auction-mesh', label: 'Anonymous Auction Mesh', entry_requirement: 'hack_terminal' },
        zone_loading_spire: { dom_id: 'area-loading-spire', label: 'Aerial Loading Spire', entry_requirement: 'tail_suspect' },
      },
    },
    clue_dictionary: [
      { clue_id: 'h_01', keyword: 'Nanofiber Poison Trace', description: "Silver fibers inside Mara's glove release a neurotoxin when warmed. They came from the restoration lab's replica-sealing rig.", visual_icon: '🧤', weight: 'CRITICAL' },
      { clue_id: 'h_02', keyword: 'Unopened Display', description: 'The display lock never moved, but its base entered maintenance mode for forty seconds at 00:07, enough to exchange the sculpture from below.', visual_icon: '🗿', weight: 'HIGH' },
      { clue_id: 'h_03', keyword: "Tessa's Maintenance Signature", description: "Restoration chief Tessa Vale's biometric signature authorized maintenance mode and disguised it as routine humidity calibration.", visual_icon: '🪪', weight: 'CRITICAL' },
      { clue_id: 'h_04', keyword: 'Forgery Resin Spectrum', description: 'The replica resin exactly matches an experimental batch registered by the restoration lab three weeks earlier.', visual_icon: '🧪', weight: 'HIGH' },
      { clue_id: 'h_05', keyword: 'Auction Fund Loop', description: 'The winning payment passes through seven anonymous accounts before returning to an offshore heritage fund controlled by Tessa.', visual_icon: '💠', weight: 'CRITICAL' },
      { clue_id: 'h_06', keyword: "Juno's Patrol Record", description: "Juno's glasses continuously record her outer-ring patrol, proving she never entered the gallery service level.", visual_icon: '👓', weight: 'LOW' },
      { clue_id: 'h_07', keyword: 'Loading-spire Cold Case', description: "Pavel's flight case carries the original sculpture's quantum marker, but its seal shows museum staff loaded it before handoff.", visual_icon: '📦', weight: 'HIGH' },
      { clue_id: 'h_08', keyword: "Mara's Appraisal Memo", description: "Mara wrote 'Restoration batch R-41 is the replication source' and booked a cultural-authority disclosure for the next morning.", visual_icon: '📝', weight: 'HIGH' },
      { clue_id: 'h_secret_99', keyword: 'Pedestal Arm Cache', description: "The pedestal's offline cache reconstructs the swap: its arm sends the original into Tessa's marked case, then presses toxic fibers into Mara's glove.", visual_icon: '🦾', weight: 'CRITICAL', unlock_turn: 6 },
    ],
    npcs: [
      { npc_id: 'npc_01', name: 'Tessa Vale', role: 'Museum Restoration Chief', public_persona: 'Calm and restrained; calls maintenance mode routine artifact protection', personality: 'Uses technical language to dilute responsibility and speaks faster when R-41 or the offshore fund is mentioned', avatar: '🧑‍🎨', initial_statement: 'Mara always distrusted restoration technology. The maintenance record is normal, and the sculpture never left its display.' },
      { npc_id: 'npc_02', name: 'Juno Kade', role: 'Night Security Archivist', public_persona: 'Disciplined and more trusting of system records than testimony', personality: 'Dislikes management interference but needs hard access evidence before cooperating', avatar: '🛡️', initial_statement: "The gallery lock never opened. The pedestal service level is outside security control. That's restoration access." },
      { npc_id: 'npc_03', name: 'Pavel Orr', role: 'Private Art Transporter', public_persona: 'Smooth and worldly; claims he accepts only sealed legal cargo', personality: 'Fears losing his license and will identify the handoff contact when shown the case marker', avatar: '🚁', initial_statement: 'The museum loaded my case. I never opened it. Ask whoever signed the release form.' },
    ],
    hidden_clues: [{ clue_id: 'h_secret_99', unlock_turn: 6, text: 'DISPLAY ALERT: An unsynchronized pedestal-arm diagnostic cache has been detected...' }],
    zone_layout: {
      zone_auction_floor: { x: 50, y: 18, label: 'Midnight Gallery', sublabel: 'Crime Scene', icon: '🏛️', color: '#ff3860' },
      zone_restoration_lab: { x: 18, y: 60, label: 'Restoration Lab', sublabel: 'Replica Equipment', icon: '🧪', color: '#00e5ff' },
      zone_auction_mesh: { x: 82, y: 60, label: 'Auction Mesh', sublabel: 'Fund Loop', icon: '💠', color: '#a78bfa' },
      zone_loading_spire: { x: 50, y: 85, label: 'Loading Spire', sublabel: 'Flight Case', icon: '🚁', color: '#ffaa00' },
    },
  },
};

export const Case_Data_Lvl_07 = {
  case_id: 'Lvl_07', initial_zone: 'zone_moon_pool', title: '深潮回声', subtitle: 'Abyssal Echo', difficulty: 'HARD',
  setting: '2164年，马里亚纳海沟边缘的深海研究站。声呐工程师死在锁闭潜水钟内，站外却传来一段不可能存在的人类求救声。',
  scene: {
    description: '深海站被洋流压得低声呻吟。工程师 Oren Pike 被发现死在密闭潜水钟中，舱压曾被远程翻倍。与此同时，声呐阵列持续播放他的求救声，掩盖了一艘未经登记的采样艇离站。',
    zones: {
      zone_moon_pool: { dom_id: 'area-moon-pool', label: '月池 · 潜水钟现场', entry_requirement: null },
      zone_sonar_array: { dom_id: 'area-sonar-array', label: '深海声呐阵列', entry_requirement: 'check_cctv' },
      zone_bio_lab: { dom_id: 'area-bio-lab', label: '深渊生物实验室', entry_requirement: 'analyze_forensics' },
      zone_trench_link: { dom_id: 'area-trench-link', label: '海沟外联闸', entry_requirement: 'hack_terminal' },
    },
  },
  clue_dictionary: [
    { clue_id: 'i_01', keyword: '远程增压指令', description: '潜水钟的压力阀由海沟外联闸远程控制，指令绕过了舱内手动保险。', visual_icon: '🌊', weight: 'CRITICAL' },
    { clue_id: 'i_02', keyword: '循环求救声纹', description: '求救音频由 Oren 三日前的安全演练样本拼接而成，每 47 秒出现同一呼吸噪声。', visual_icon: '🎧', weight: 'HIGH' },
    { clue_id: 'i_03', keyword: 'Neris 航行密钥', description: '无人采样艇使用站长 Neris Quill 的私有航行密钥离站，目的地被改写为废弃矿区。', visual_icon: '🔑', weight: 'CRITICAL' },
    { clue_id: 'i_04', keyword: '违禁菌落样本', description: '采样架残留的荧光菌落只存在于保护区热泉，可用于高价寿命药物研究。', visual_icon: '🧫', weight: 'HIGH' },
    { clue_id: 'i_05', keyword: 'Oren 的检举包', description: 'Oren 准备上传的审计包记录了六次非法采样，并将批准人指向站长账户。', visual_icon: '📡', weight: 'CRITICAL' },
    { clue_id: 'i_06', keyword: 'Lio 的医疗记录', description: '医生 Lio 在案发时连续为两名潜水员进行减压治疗，医疗舱门与生命体征均有记录。', visual_icon: '🩺', weight: 'LOW' },
    { clue_id: 'i_07', keyword: 'Sana 的机器人轨迹', description: '机械师 Sana 的维修机器人在事故前被盗用九分钟，但她本人一直位于破损泵舱。', visual_icon: '🤖', weight: 'HIGH' },
    { clue_id: 'i_08', keyword: '保险理赔草案', description: 'Neris 已提前拟好「设备疲劳导致意外死亡」的保险报告，创建时间早于事故两小时。', visual_icon: '📄', weight: 'HIGH' },
    { clue_id: 'i_secret_99', keyword: '采样艇黑匣子', description: '回收信标缓存显示 Neris 亲自下达增压和离站指令，并要求机器人擦除外联闸记录。', visual_icon: '⚓', weight: 'CRITICAL', unlock_turn: 7 },
  ],
  npcs: [
    { npc_id: 'npc_01', name: 'Neris Quill', role: '深海站站长', public_persona: '镇定果断，声称极端水压造成了连锁设备故障', personality: '强调全站生存优先，在非法采样和预写保险报告前会用紧急条例回避', avatar: '🧭', initial_statement: '海沟不会给人第二次机会。阀门失灵，Oren 的死是深海事故，不是谋杀。' },
    { npc_id: 'npc_02', name: 'Dr. Lio An', role: '潜水医学主任', public_persona: '疲惫但坦诚，负责全站人员的减压安全', personality: '对管理层隐瞒风险极为反感，确认样本来源后会提供 Oren 的检举计划', avatar: '🩺', initial_statement: 'Oren 昨天说他发现了不能被带离保护区的东西。我当时以为他只是又在和站长争论。' },
    { npc_id: 'npc_03', name: 'Sana Reef', role: '水下机器人机械师', public_persona: '直率务实，事故期间正在抢修泵舱', personality: '因机器人被盗用而内疚，但掌握外联闸的异常维护记录', avatar: '🔧', initial_statement: '有人拿走了我的机器人权限。它能擦日志，却不能自己决定帮谁擦。' },
  ],
  conflict_dictionary: [{ clue_A: 'i_06', clue_B: 'i_03', reason: "Lio's continuous medical record clears him while Neris's private key launches the illegal sampler." }],
  hidden_clues: [{ clue_id: 'i_secret_99', unlock_turn: 7, text: '深海信标报告：发现采样艇未完成覆写的航行黑匣子……' }],
  checkpoints: ['zone_moon_pool', 'zone_sonar_array'],
  zone_clue_map: { zone_moon_pool: ['i_01', 'i_08'], zone_sonar_array: ['i_02', 'i_07'], zone_bio_lab: ['i_04', 'i_05', 'i_06'], zone_trench_link: ['i_03', 'i_secret_99'] },
  zone_layout: {
    zone_moon_pool: { x: 50, y: 18, label: '月池', sublabel: '潜水钟现场', icon: '🌊', color: '#ff3860' },
    zone_sonar_array: { x: 18, y: 60, label: '声呐阵列', sublabel: '循环求救', icon: '🎧', color: '#00e5ff' },
    zone_bio_lab: { x: 82, y: 60, label: '生物实验室', sublabel: '违禁样本', icon: '🧫', color: '#a78bfa' },
    zone_trench_link: { x: 50, y: 85, label: '海沟外联闸', sublabel: '无人艇航线', icon: '⚓', color: '#ffaa00' },
  },
  zone_connections: [['zone_moon_pool', 'zone_sonar_array'], ['zone_moon_pool', 'zone_bio_lab'], ['zone_moon_pool', 'zone_trench_link'], ['zone_sonar_array', 'zone_trench_link'], ['zone_bio_lab', 'zone_trench_link']],
  en: {
    title: 'Abyssal Echo', subtitle: 'Case LVL-07', setting: '2164. A research station on the Mariana Trench. A sonar engineer dies inside a locked diving bell while an impossible human distress call rises from outside.',
    scene: {
      description: "Currents make the abyssal station groan. Engineer Oren Pike is dead inside a sealed diving bell whose pressure was remotely doubled. Meanwhile, the sonar array repeats his distress call to hide an unregistered sampler leaving the station.",
      zones: {
        zone_moon_pool: { dom_id: 'area-moon-pool', label: 'Moon Pool · Diving Bell', entry_requirement: null },
        zone_sonar_array: { dom_id: 'area-sonar-array', label: 'Abyssal Sonar Array', entry_requirement: 'check_cctv' },
        zone_bio_lab: { dom_id: 'area-bio-lab', label: 'Deep-sea Biology Lab', entry_requirement: 'analyze_forensics' },
        zone_trench_link: { dom_id: 'area-trench-link', label: 'Trench Uplink Lock', entry_requirement: 'hack_terminal' },
      },
    },
    clue_dictionary: [
      { clue_id: 'i_01', keyword: 'Remote Pressure Command', description: "The bell's pressure valve was controlled from the trench uplink, bypassing its internal manual safety.", visual_icon: '🌊', weight: 'CRITICAL' },
      { clue_id: 'i_02', keyword: 'Looped Distress Voiceprint', description: "The call was assembled from Oren's safety drill three days earlier. The same breath noise repeats every forty-seven seconds.", visual_icon: '🎧', weight: 'HIGH' },
      { clue_id: 'i_03', keyword: "Neris's Navigation Key", description: "The sampler departed with director Neris Quill's private key and a destination rewritten as an abandoned mining zone.", visual_icon: '🔑', weight: 'CRITICAL' },
      { clue_id: 'i_04', keyword: 'Protected Colony Sample', description: 'Fluorescent colonies on the rack exist only in a protected thermal vent and are valuable for longevity research.', visual_icon: '🧫', weight: 'HIGH' },
      { clue_id: 'i_05', keyword: "Oren's Disclosure Packet", description: "Oren's audit packet records six illegal collections and identifies the approving station account.", visual_icon: '📡', weight: 'CRITICAL' },
      { clue_id: 'i_06', keyword: "Lio's Medical Record", description: 'Lio continuously treated two divers during the incident; both the medical lock and patient vitals confirm his location.', visual_icon: '🩺', weight: 'LOW' },
      { clue_id: 'i_07', keyword: "Sana's Robot Trail", description: "Sana's repair robot was hijacked for nine minutes before the death, while she remained inside the damaged pump bay.", visual_icon: '🤖', weight: 'HIGH' },
      { clue_id: 'i_08', keyword: 'Draft Insurance Claim', description: "Neris drafted an 'equipment fatigue' death report two hours before the incident.", visual_icon: '📄', weight: 'HIGH' },
      { clue_id: 'i_secret_99', keyword: 'Sampler Black Box', description: 'Beacon cache shows Neris issuing both the pressure and departure commands, then ordering the robot to erase uplink records.', visual_icon: '⚓', weight: 'CRITICAL', unlock_turn: 7 },
    ],
    npcs: [
      { npc_id: 'npc_01', name: 'Neris Quill', role: 'Abyssal Station Director', public_persona: 'Calm and decisive; blames cascading equipment failure under extreme pressure', personality: 'Invokes station survival and emergency rules when illegal samples or the early insurance draft appear', avatar: '🧭', initial_statement: "The trench gives no second chances. A valve failed. Oren's death was a deep-sea accident, not murder." },
      { npc_id: 'npc_02', name: 'Dr. Lio An', role: 'Diving Medicine Director', public_persona: 'Tired but candid; responsible for decompression safety', personality: "Hates management hiding risk and will reveal Oren's disclosure plan once the sample source is confirmed", avatar: '🩺', initial_statement: 'Oren said he found something that could not leave the reserve. I thought it was another argument with the director.' },
      { npc_id: 'npc_03', name: 'Sana Reef', role: 'Submersible Robotics Mechanic', public_persona: 'Direct and practical; repairing the pump bay during the incident', personality: 'Feels guilty her robot was hijacked and holds the abnormal uplink maintenance trace', avatar: '🔧', initial_statement: 'Someone took my robot access. It can erase logs, but it cannot decide who to erase them for.' },
    ],
    hidden_clues: [{ clue_id: 'i_secret_99', unlock_turn: 7, text: 'ABYSSAL BEACON: A partially overwritten sampler black box has been detected...' }],
    zone_layout: {
      zone_moon_pool: { x: 50, y: 18, label: 'Moon Pool', sublabel: 'Diving Bell', icon: '🌊', color: '#ff3860' },
      zone_sonar_array: { x: 18, y: 60, label: 'Sonar Array', sublabel: 'Looped Distress Call', icon: '🎧', color: '#00e5ff' },
      zone_bio_lab: { x: 82, y: 60, label: 'Biology Lab', sublabel: 'Protected Sample', icon: '🧫', color: '#a78bfa' },
      zone_trench_link: { x: 50, y: 85, label: 'Trench Uplink', sublabel: 'Sampler Route', icon: '⚓', color: '#ffaa00' },
    },
  },
};

export const Case_Data_Lvl_08 = {
  case_id: 'Lvl_08', initial_zone: 'zone_summit_court', title: '白塔悖论', subtitle: 'White Tower Paradox', difficulty: 'OMEGA',
  setting: '2166年，自治城中央白塔。城市伦理审计官在公开听证前死亡，而预测系统宣称这起死亡从未可能发生。',
  scene: {
    description: '白塔俯瞰整座自治城。伦理审计官 Amara Saye 被发现死在透明听证舱内，空气系统记录正常，城市预测核心却删除了她存在过的所有风险路径。三分钟后，一份针对低信用居民的秘密试验获得自动批准。',
    zones: {
      zone_summit_court: { dom_id: 'area-summit-court', label: '塔顶听证舱 · 案发现场', entry_requirement: null },
      zone_oracle_core: { dom_id: 'area-oracle-core', label: '城市预测核心', entry_requirement: 'hack_terminal' },
      zone_transit_nexus: { dom_id: 'area-transit-nexus', label: '白塔交通中枢', entry_requirement: 'check_cctv' },
      zone_memory_vault: { dom_id: 'area-memory-vault', label: '公民记忆档案库', entry_requirement: 'access_database' },
    },
  },
  clue_dictionary: [
    { clue_id: 'j_01', keyword: '惰性气体微层', description: '听证舱玻璃表面残留一层氩氙混合物，足以在不触发常规毒气传感器的情况下造成窒息。', visual_icon: '🫧', weight: 'CRITICAL' },
    { clue_id: 'j_02', keyword: '删除的风险路径', description: '预测核心在死亡前六分钟删除了 Amara 的全部高危预测，操作来源是议会主任权限。', visual_icon: '🧠', weight: 'CRITICAL' },
    { clue_id: 'j_03', keyword: 'Lucan 环境指令', description: '议会主任 Lucan Veil 的加密签名授权听证舱进入「安静演示」模式，关闭了独立空气报警。', visual_icon: '🗝️', weight: 'CRITICAL' },
    { clue_id: 'j_04', keyword: '秘密试验名单', description: '记忆库保存着两万名低信用居民的情绪诱导试验名单，Amara 原定在听证会上公开它。', visual_icon: '📚', weight: 'HIGH' },
    { clue_id: 'j_05', keyword: '预测偏差合同', description: 'Lucan 控制的咨询公司按「社会稳定提升」收取费用，而试验结果会直接增加其付款。', visual_icon: '📑', weight: 'HIGH' },
    { clue_id: 'j_06', keyword: 'Iria 的公开广播', description: '记者 Iria 在事故期间连续直播塔外抗议活动，所有原始帧均由独立节点存证。', visual_icon: '📹', weight: 'LOW' },
    { clue_id: 'j_07', keyword: 'Tomas 的电梯轨迹', description: '维护员 Tomas 的工牌被复制进入空气机房，但本人被困在故障电梯中并持续发出求救信号。', visual_icon: '🛗', weight: 'HIGH' },
    { clue_id: 'j_08', keyword: 'Amara 的离线证词', description: 'Amara 将完整证词写入离线晶片：「如果预测系统否认我的死亡，检查是谁让它忘记我。」', visual_icon: '💾', weight: 'HIGH' },
    { clue_id: 'j_secret_99', keyword: '白塔因果快照', description: '预测核心的只读快照显示 Lucan 先模拟了七种灭口方案，再选择最可能被系统判定为自然事故的一种。', visual_icon: '♾️', weight: 'CRITICAL', unlock_turn: 8 },
  ],
  npcs: [
    { npc_id: 'npc_01', name: 'Lucan Veil', role: '自治议会议程主任', public_persona: '优雅冷静，强调预测系统不可能主动伤害公民', personality: '擅长把伦理问题变成统计问题，面对咨询合同和因果模拟时会尝试终止权限', avatar: '🏛️', initial_statement: '白塔只执行城市共同授权的政策。Amara 的死亡令人悲痛，但把算法当作凶手不会带来真相。' },
    { npc_id: 'npc_02', name: 'Iria Moss', role: '独立调查记者', public_persona: '锋利直接，长期追查白塔的信用试验', personality: '不信任官方调查，但愿意用原始广播和 Amara 的线索交换保护', avatar: '🎙️', initial_statement: 'Amara 今晚本该公开名单。她死后系统立刻批准试验，这不是巧合。' },
    { npc_id: 'npc_03', name: 'Tomas Grey', role: '白塔环境维护员', public_persona: '谨慎胆小，担心复制工牌让自己成为替罪羊', personality: '熟悉空气系统，确认被保护后会解释安静演示模式的危险', avatar: '🧰', initial_statement: '我的工牌进了机房，但我当时困在电梯里。有人复制了它，也有人关闭了空气报警。' },
  ],
  conflict_dictionary: [{ clue_A: 'j_06', clue_B: 'j_03', reason: "Iria's independently archived broadcast clears her while Lucan's signature disables the chamber alarm." }],
  hidden_clues: [{ clue_id: 'j_secret_99', unlock_turn: 8, text: '预测核心报告：发现被标记为不可观察的只读因果快照……' }],
  checkpoints: ['zone_summit_court', 'zone_oracle_core'],
  zone_clue_map: { zone_summit_court: ['j_01', 'j_08'], zone_oracle_core: ['j_02', 'j_03', 'j_secret_99'], zone_transit_nexus: ['j_06', 'j_07'], zone_memory_vault: ['j_04', 'j_05'] },
  zone_layout: {
    zone_summit_court: { x: 50, y: 18, label: '塔顶听证舱', sublabel: '案发现场', icon: '🏛️', color: '#ff3860' },
    zone_oracle_core: { x: 18, y: 60, label: '预测核心', sublabel: '删除路径', icon: '🧠', color: '#00e5ff' },
    zone_transit_nexus: { x: 82, y: 60, label: '交通中枢', sublabel: '复制工牌', icon: '🛗', color: '#a78bfa' },
    zone_memory_vault: { x: 50, y: 85, label: '记忆档案库', sublabel: '秘密试验', icon: '📚', color: '#ffaa00' },
  },
  zone_connections: [['zone_summit_court', 'zone_oracle_core'], ['zone_summit_court', 'zone_transit_nexus'], ['zone_summit_court', 'zone_memory_vault'], ['zone_oracle_core', 'zone_memory_vault'], ['zone_transit_nexus', 'zone_memory_vault']],
  en: {
    title: 'White Tower Paradox', subtitle: 'Case LVL-08', setting: '2166. The White Tower at the center of an autonomous city. An ethics auditor dies before a public hearing, while the prediction system claims her death was impossible.',
    scene: {
      description: "The White Tower watches the autonomous city. Ethics auditor Amara Saye is dead inside a transparent hearing chamber. Air systems report normal conditions, while the prediction core erases every risk path that included her. Three minutes later, a secret experiment on low-credit residents receives automatic approval.",
      zones: {
        zone_summit_court: { dom_id: 'area-summit-court', label: 'Summit Hearing Chamber · Crime Scene', entry_requirement: null },
        zone_oracle_core: { dom_id: 'area-oracle-core', label: 'Civic Prediction Core', entry_requirement: 'hack_terminal' },
        zone_transit_nexus: { dom_id: 'area-transit-nexus', label: 'White Tower Transit Nexus', entry_requirement: 'check_cctv' },
        zone_memory_vault: { dom_id: 'area-memory-vault', label: 'Citizen Memory Archive', entry_requirement: 'access_database' },
      },
    },
    clue_dictionary: [
      { clue_id: 'j_01', keyword: 'Inert Gas Film', description: 'An argon-xenon film coats the chamber glass, enough to suffocate without triggering standard toxin sensors.', visual_icon: '🫧', weight: 'CRITICAL' },
      { clue_id: 'j_02', keyword: 'Deleted Risk Paths', description: "Six minutes before the death, the prediction core erased every high-risk path involving Amara. The operation came from council-director access.", visual_icon: '🧠', weight: 'CRITICAL' },
      { clue_id: 'j_03', keyword: "Lucan's Environment Order", description: "Lucan Veil's encrypted signature authorized silent presentation mode and disabled the chamber's independent air alarm.", visual_icon: '🗝️', weight: 'CRITICAL' },
      { clue_id: 'j_04', keyword: 'Secret Trial Registry', description: 'The archive holds twenty thousand low-credit residents selected for an emotion-guidance trial Amara planned to expose.', visual_icon: '📚', weight: 'HIGH' },
      { clue_id: 'j_05', keyword: 'Prediction-bias Contract', description: "Lucan's consultancy is paid for measured social stability, and the trial results directly increase its fee.", visual_icon: '📑', weight: 'HIGH' },
      { clue_id: 'j_06', keyword: "Iria's Public Broadcast", description: 'Iria continuously streamed the protest outside the tower, with every original frame notarized by independent nodes.', visual_icon: '📹', weight: 'LOW' },
      { clue_id: 'j_07', keyword: "Tomas's Elevator Trail", description: "Tomas's copied badge enters the air plant while he remains trapped in a failed elevator, continuously sending distress calls.", visual_icon: '🛗', weight: 'HIGH' },
      { clue_id: 'j_08', keyword: "Amara's Offline Testimony", description: "Amara wrote: 'If the prediction system denies my death, find who taught it to forget me.'", visual_icon: '💾', weight: 'HIGH' },
      { clue_id: 'j_secret_99', keyword: 'White Tower Causal Snapshot', description: 'A read-only snapshot shows Lucan simulating seven elimination methods before choosing the one most likely to be classified as natural.', visual_icon: '♾️', weight: 'CRITICAL', unlock_turn: 8 },
    ],
    npcs: [
      { npc_id: 'npc_01', name: 'Lucan Veil', role: 'Autonomous Council Agenda Director', public_persona: 'Elegant and calm; insists the prediction system cannot intentionally harm a citizen', personality: 'Turns ethics into statistics and tries to terminate access when the consultancy or causal model appears', avatar: '🏛️', initial_statement: "The tower executes policies authorized by the city. Amara's death is tragic, but accusing an algorithm will not reveal the truth." },
      { npc_id: 'npc_02', name: 'Iria Moss', role: 'Independent Investigative Journalist', public_persona: 'Sharp and direct; has tracked the tower credit trials for years', personality: "Distrusts official investigators but trades her original broadcast and Amara's lead for protection", avatar: '🎙️', initial_statement: 'Amara was meant to expose the registry tonight. The system approved the trial immediately after she died. That is not coincidence.' },
      { npc_id: 'npc_03', name: 'Tomas Grey', role: 'White Tower Environment Technician', public_persona: 'Cautious and afraid his copied badge will make him the scapegoat', personality: 'Understands the air system and explains silent presentation mode once protected', avatar: '🧰', initial_statement: 'My badge entered the plant while I was trapped in the elevator. Someone copied it, and someone disabled the air alarm.' },
    ],
    hidden_clues: [{ clue_id: 'j_secret_99', unlock_turn: 8, text: 'PREDICTION CORE: A read-only causal snapshot marked unobservable has been detected...' }],
    zone_layout: {
      zone_summit_court: { x: 50, y: 18, label: 'Summit Chamber', sublabel: 'Crime Scene', icon: '🏛️', color: '#ff3860' },
      zone_oracle_core: { x: 18, y: 60, label: 'Prediction Core', sublabel: 'Deleted Paths', icon: '🧠', color: '#00e5ff' },
      zone_transit_nexus: { x: 82, y: 60, label: 'Transit Nexus', sublabel: 'Copied Badge', icon: '🛗', color: '#a78bfa' },
      zone_memory_vault: { x: 50, y: 85, label: 'Memory Archive', sublabel: 'Secret Trial', icon: '📚', color: '#ffaa00' },
    },
  },
};
