// Additional public case files. Culprits, final truth and valid evidence edges
// remain in the server-only Cloudflare rules registry.

export const Case_Data_Lvl_04 = {
  case_id: 'Lvl_04',
  initial_zone: 'zone_cryo_chamber',
  title: '零度回声',
  subtitle: 'Zero Echo',
  difficulty: 'HARD',
  setting: '2161年，极地气候档案站。首席研究员在零下六十度的密封冷库中死亡，温控系统却声称整夜正常。',
  scene: {
    description: '暴风雪切断了极地档案站与外界的联系。Dr. Noor 被发现倒在密封冷库内，防寒服上覆盖着不自然的霜裂纹。冷库门没有强行开启痕迹，温控记录却缺失了精确的十一分钟。',
    zones: {
      zone_cryo_chamber: { dom_id: 'area-cryo-chamber', label: '低温冷库 · 案发现场', entry_requirement: null },
      zone_control_room: { dom_id: 'area-control-room', label: '环境控制室', entry_requirement: 'hack_terminal' },
      zone_maintenance: { dom_id: 'area-maintenance', label: '维护隧道', entry_requirement: 'search_area' },
      zone_archive_lab: { dom_id: 'area-archive-lab', label: '气候档案实验室', entry_requirement: 'access_database' },
    },
  },
  clue_dictionary: [
    { clue_id: 'f_01', keyword: '异常霜裂纹', description: '防寒服上的霜裂纹由瞬间液氮喷射形成，而不是环境降温造成；喷射方向来自冷库顶部维护口。', visual_icon: '❄️', weight: 'CRITICAL' },
    { clue_id: 'f_02', keyword: '十一分钟日志缺口', description: '温控记录在 03:12 至 03:23 被替换成重复数据，覆盖方式需要管理员权限。', visual_icon: '📉', weight: 'CRITICAL' },
    { clue_id: 'f_03', keyword: '维护无人机残留', description: '顶部管道内发现微型履带磨屑和液氮结晶，与站内 D-4 维护无人机型号一致。', visual_icon: '🤖', weight: 'HIGH' },
    { clue_id: 'f_04', keyword: 'Elias 管理令牌', description: '控制室缓存显示 03:11 使用了站务主管 Elias 的管理员令牌，随后远程唤醒 D-4 无人机。', visual_icon: '🔑', weight: 'CRITICAL' },
    { clue_id: 'f_05', keyword: '气候模型交易', description: '档案数据库中发现一份未完成的境外交易草案，出售对象正是 Dr. Noor 即将公开的极地预测模型。', visual_icon: '🗃️', weight: 'HIGH' },
    { clue_id: 'f_06', keyword: 'Mira 的维修影像', description: '外部机库摄像头连续记录工程师 Mira 在 02:50 至 03:35 修复风机，她无法进入冷库区。', visual_icon: '🎥', weight: 'LOW' },
    { clue_id: 'f_07', keyword: '阀门工具痕', description: '维护隧道的液氮旁路阀有新鲜电动扳手痕迹，扭矩设置与 D-4 无人机默认参数相同。', visual_icon: '🔧', weight: 'HIGH' },
    { clue_id: 'f_08', keyword: '审计预约信息', description: 'Dr. Noor 在遇害前预约了清晨审计，并写道「主管账户的外传记录足以定罪」。', visual_icon: '📨', weight: 'HIGH' },
    { clue_id: 'f_secret_99', keyword: '无人机覆盖缓存', description: 'D-4 的隐藏缓存保留了一条被删除的路线：控制室—维护隧道—冷库顶部维护口，并带有 Elias 的令牌签名。', visual_icon: '🧊', weight: 'CRITICAL', unlock_turn: 7 },
  ],
  npcs: [
    { npc_id: 'npc_01', name: 'Elias Venn', role: '档案站站务主管', public_persona: '沉着可靠，声称温控事故源于暴风雪导致的设备故障', personality: '习惯掌控谈话，在被问及管理员令牌时会迅速转向程序责任', avatar: '🧥', initial_statement: '这座站已经运行二十年。暴风雪让系统失常，Noor 的死是一场可怕的事故。' },
    { npc_id: 'npc_02', name: 'Mira Sol', role: '低温设备工程师', public_persona: '技术熟练但脾气急躁，曾与 Noor 公开争执', personality: '对设备问题直言不讳，被怀疑时会愤怒，但时间线非常清楚', avatar: '🛠️', initial_statement: '我确实和 Noor 吵过，但我整晚都在外部机库。去查风机摄像头。' },
    { npc_id: 'npc_03', name: 'Sol Adebayo', role: '联合气候署审计员', public_persona: '谨慎中立，清晨刚抵达档案站', personality: '重视书面证据，不会轻易评价任何人，但掌握 Noor 的审计计划', avatar: '📋', initial_statement: 'Noor 要我核查一次模型外传。她说问题来自管理层，但没有在通讯中写出姓名。' },
  ],
  conflict_dictionary: [{ clue_A: 'f_06', clue_B: 'f_04', reason: "Mira's continuous exterior footage clears her while Elias's token controls the drone." }],
  hidden_clues: [{ clue_id: 'f_secret_99', unlock_turn: 7, text: '维护网络检测到 D-4 无人机尚未完全覆写的导航缓存……' }],
  checkpoints: ['zone_cryo_chamber', 'zone_control_room'],
  zone_clue_map: {
    zone_cryo_chamber: ['f_01', 'f_03'],
    zone_control_room: ['f_02', 'f_04', 'f_secret_99'],
    zone_maintenance: ['f_07', 'f_06'],
    zone_archive_lab: ['f_05', 'f_08'],
  },
  zone_layout: {
    zone_cryo_chamber: { x: 50, y: 18, label: '低温冷库', sublabel: '案发现场', icon: '🧊', color: '#ff3860' },
    zone_control_room: { x: 82, y: 58, label: '环境控制室', sublabel: '权限记录', icon: '🖥️', color: '#a78bfa' },
    zone_maintenance: { x: 18, y: 58, label: '维护隧道', sublabel: '无人机路线', icon: '🔧', color: '#00e5ff' },
    zone_archive_lab: { x: 50, y: 85, label: '档案实验室', sublabel: '交易动机', icon: '🗄️', color: '#ffaa00' },
  },
  zone_connections: [['zone_cryo_chamber', 'zone_control_room'], ['zone_cryo_chamber', 'zone_maintenance'], ['zone_cryo_chamber', 'zone_archive_lab'], ['zone_control_room', 'zone_archive_lab'], ['zone_maintenance', 'zone_archive_lab']],
  en: {
    title: 'Zero Echo',
    subtitle: 'Case LVL-04',
    setting: '2161. A polar climate archive. The chief researcher dies inside a sealed chamber at minus sixty, while climate control reports a normal night.',
    scene: {
      description: "A blizzard severs the polar archive from the outside world. Dr. Noor is found inside a sealed cold vault, her thermal suit covered in unnatural frost fractures. The door shows no forced entry, but exactly eleven minutes are missing from the climate-control record.",
      zones: {
        zone_cryo_chamber: { dom_id: 'area-cryo-chamber', label: 'Cryogenic Vault · Crime Scene', entry_requirement: null },
        zone_control_room: { dom_id: 'area-control-room', label: 'Environmental Control', entry_requirement: 'hack_terminal' },
        zone_maintenance: { dom_id: 'area-maintenance', label: 'Maintenance Tunnel', entry_requirement: 'search_area' },
        zone_archive_lab: { dom_id: 'area-archive-lab', label: 'Climate Archive Lab', entry_requirement: 'access_database' },
      },
    },
    clue_dictionary: [
      { clue_id: 'f_01', keyword: 'Abnormal Frost Fractures', description: "The suit's fractures came from an instantaneous liquid-nitrogen jet, not ambient cooling. The spray originated at the overhead service hatch.", visual_icon: '❄️', weight: 'CRITICAL' },
      { clue_id: 'f_02', keyword: 'Eleven-minute Log Gap', description: 'Climate records from 03:12 to 03:23 were replaced with looped data. The overwrite required administrator access.', visual_icon: '📉', weight: 'CRITICAL' },
      { clue_id: 'f_03', keyword: 'Maintenance Drone Residue', description: 'Micro-track shavings and nitrogen crystals in the overhead duct match the station D-4 maintenance drone.', visual_icon: '🤖', weight: 'HIGH' },
      { clue_id: 'f_04', keyword: "Elias's Admin Token", description: "Control cache shows Elias's administrator token remotely waking the D-4 drone at 03:11.", visual_icon: '🔑', weight: 'CRITICAL' },
      { clue_id: 'f_05', keyword: 'Climate Model Deal', description: 'An unfinished foreign sale draft offers the same polar prediction model Dr. Noor planned to publish.', visual_icon: '🗃️', weight: 'HIGH' },
      { clue_id: 'f_06', keyword: "Mira's Repair Footage", description: 'Exterior hangar cameras continuously show Mira repairing a turbine from 02:50 to 03:35. She could not enter the vault sector.', visual_icon: '🎥', weight: 'LOW' },
      { clue_id: 'f_07', keyword: 'Valve Tool Marks', description: "Fresh powered-wrench marks on the nitrogen bypass valve use the D-4 drone's default torque setting.", visual_icon: '🔧', weight: 'HIGH' },
      { clue_id: 'f_08', keyword: 'Audit Appointment', description: "Before her death, Noor scheduled a dawn audit and wrote: 'The supervisor account's export record is enough to convict.'", visual_icon: '📨', weight: 'HIGH' },
      { clue_id: 'f_secret_99', keyword: 'Drone Override Cache', description: "The D-4 hidden cache retains a deleted route from control to the tunnel and vault hatch, signed with Elias's token.", visual_icon: '🧊', weight: 'CRITICAL', unlock_turn: 7 },
    ],
    npcs: [
      { npc_id: 'npc_01', name: 'Elias Venn', role: 'Archive Station Supervisor', public_persona: 'Calm and dependable; claims the blizzard caused a climate-control accident', personality: 'Controls every conversation and redirects questions about his token toward procedural responsibility', avatar: '🧥', initial_statement: "This station has operated for twenty years. The blizzard destabilized the system. Noor's death was a terrible accident." },
      { npc_id: 'npc_02', name: 'Mira Sol', role: 'Cryogenic Systems Engineer', public_persona: 'Highly skilled but hot-tempered; publicly argued with Noor', personality: 'Blunt about equipment failures and furious when accused, but precise about her timeline', avatar: '🛠️', initial_statement: 'I argued with Noor, yes. I was in the exterior hangar all night. Check the turbine cameras.' },
      { npc_id: 'npc_03', name: 'Sol Adebayo', role: 'Climate Authority Auditor', public_persona: 'Cautious and neutral; arrived at the station before dawn', personality: "Relies on documentary evidence and holds Noor's audit plan without rushing to judgment", avatar: '📋', initial_statement: 'Noor asked me to examine a model export. She said the problem came from management, but never named anyone in writing.' },
    ],
    hidden_clues: [{ clue_id: 'f_secret_99', unlock_turn: 7, text: 'MAINTENANCE ALERT: A partially overwritten D-4 navigation cache has been detected...' }],
    zone_layout: {
      zone_cryo_chamber: { x: 50, y: 18, label: 'Cryogenic Vault', sublabel: 'Crime Scene', icon: '🧊', color: '#ff3860' },
      zone_control_room: { x: 82, y: 58, label: 'Control Room', sublabel: 'Access Records', icon: '🖥️', color: '#a78bfa' },
      zone_maintenance: { x: 18, y: 58, label: 'Maintenance Tunnel', sublabel: 'Drone Route', icon: '🔧', color: '#00e5ff' },
      zone_archive_lab: { x: 50, y: 85, label: 'Archive Lab', sublabel: 'Trade Motive', icon: '🗄️', color: '#ffaa00' },
    },
  },
};

export const Case_Data_Lvl_05 = {
  case_id: 'Lvl_05',
  initial_zone: 'zone_docking_hub',
  title: '天穹失联',
  subtitle: 'Skyfall Silence',
  difficulty: 'OMEGA',
  setting: '2163年，轨道电梯「天穹一号」。一名货运船长在真空救生舱中死亡，事故同时抹除了整条军用货柜航线。',
  scene: {
    description: '轨道电梯在雷暴层上方静默运行。Captain Jonah Vale 被发现困在已经泄压的救生舱内，舱门从外部保持锁定。就在同一分钟，一只未登记的军用货柜从港务系统中消失。',
    zones: {
      zone_docking_hub: { dom_id: 'area-docking-hub', label: '轨道泊位 · 救生舱', entry_requirement: null },
      zone_tether_control: { dom_id: 'area-tether-control', label: '缆索控制中心', entry_requirement: 'hack_terminal' },
      zone_cargo_vault: { dom_id: 'area-cargo-vault', label: '零重力货仓', entry_requirement: 'search_area' },
      zone_observation_ring: { dom_id: 'area-observation-ring', label: '观测环 · 监控阵列', entry_requirement: 'check_cctv' },
    },
  },
  clue_dictionary: [
    { clue_id: 'g_01', keyword: '定向泄压痕迹', description: '救生舱泄压阀由外部诊断端口发送指令开启，机械保险仍完整，排除船长自行操作。', visual_icon: '🛰️', weight: 'CRITICAL' },
    { clue_id: 'g_02', keyword: '伪造船长指令', description: '港务系统记录一条 Jonah 的货柜放行指令，但签名延迟与本人神经密钥不符，是高权限复制品。', visual_icon: '🪪', weight: 'CRITICAL' },
    { clue_id: 'g_03', keyword: '武器级同位素', description: '消失货柜所在泊位残留武器级氚化物微粒，货物申报却写着医疗冷却剂。', visual_icon: '☢️', weight: 'HIGH' },
    { clue_id: 'g_04', keyword: 'Rook 主控访问', description: '电梯主管 Cassian Rook 的主控账户在事故前两分钟打开诊断端口，并关闭救生舱报警转发。', visual_icon: '🗝️', weight: 'CRITICAL' },
    { clue_id: 'g_05', keyword: 'Yara 的校准记录', description: '缆索工程师 Yara 在事故期间持续执行公开的张力校准，六个独立传感器均能证明其位置。', visual_icon: '📐', weight: 'LOW' },
    { clue_id: 'g_06', keyword: 'Ivo 的影子航单', description: '快递员 Ivo 的腕端保存一份未上链航单，收货人代号与 Rook 私人公司的加密标识一致。', visual_icon: '📦', weight: 'HIGH' },
    { clue_id: 'g_07', keyword: '监控视差残影', description: '被循环播放的观测环影像中，星背景视差每 18 秒跳变一次，证明有人用短片覆盖真实监控。', visual_icon: '🎞️', weight: 'HIGH' },
    { clue_id: 'g_08', keyword: 'Jonah 紧急信标', description: '船长死亡前发出一段残缺信标：「主管在卖军用货……不要相信放行记录。」', visual_icon: '📡', weight: 'HIGH' },
    { clue_id: 'g_secret_99', keyword: '离线货柜账本', description: '货仓维护节点中恢复出离线账本，记录 Rook 与 Ivo 连续六次转移军用货柜，以及本次的灭口指令。', visual_icon: '🌌', weight: 'CRITICAL', unlock_turn: 8 },
  ],
  npcs: [
    { npc_id: 'npc_01', name: 'Cassian Rook', role: '轨道电梯主管', public_persona: '冷静威严，强调事故发生时自己正在协调雷暴层避险', personality: '擅长引用安全条例压制质疑，对私人公司和主控账户异常极其敏感', avatar: '🧑‍✈️', initial_statement: 'Jonah 违反了救生舱规程。我们失去了一位船长，但不能让悲剧演变成毫无根据的指控。' },
    { npc_id: 'npc_02', name: 'Yara Sen', role: '缆索系统工程师', public_persona: '严谨寡言，负责电梯最危险的张力校准', personality: '只相信传感器数据，面对政治施压时会变得强硬', avatar: '👩‍🚀', initial_statement: '救生舱不是自己泄压的。有人通过诊断网开了阀。我的校准记录可以证明我不在泊位。' },
    { npc_id: 'npc_03', name: 'Ivo Marek', role: '独立轨道快递员', public_persona: '圆滑健谈，声称只是替客户运送合法冷却剂', personality: '回避货物来源，在看到航单与同位素证据时会迅速寻找交易空间', avatar: '🧑‍🚀', initial_statement: '我只负责把密封箱送到指定泊位。里面是什么，我没有权限也没有兴趣知道。' },
  ],
  conflict_dictionary: [{ clue_A: 'g_05', clue_B: 'g_04', reason: "Yara's independent calibration sensors clear her while Rook's account opened the fatal diagnostic path." }],
  hidden_clues: [{ clue_id: 'g_secret_99', unlock_turn: 8, text: '货仓维护节点报告：发现未同步至港务链的离线交易扇区……' }],
  checkpoints: ['zone_docking_hub', 'zone_tether_control'],
  zone_clue_map: {
    zone_docking_hub: ['g_01', 'g_02', 'g_08'],
    zone_tether_control: ['g_04', 'g_05'],
    zone_cargo_vault: ['g_03', 'g_06', 'g_secret_99'],
    zone_observation_ring: ['g_07'],
  },
  zone_layout: {
    zone_docking_hub: { x: 50, y: 18, label: '轨道泊位', sublabel: '救生舱现场', icon: '🛰️', color: '#ff3860' },
    zone_tether_control: { x: 18, y: 60, label: '缆索控制中心', sublabel: '主控权限', icon: '🗼', color: '#00e5ff' },
    zone_cargo_vault: { x: 82, y: 60, label: '零重力货仓', sublabel: '消失货柜', icon: '📦', color: '#a78bfa' },
    zone_observation_ring: { x: 50, y: 85, label: '观测环', sublabel: '监控残影', icon: '🔭', color: '#ffaa00' },
  },
  zone_connections: [['zone_docking_hub', 'zone_tether_control'], ['zone_docking_hub', 'zone_cargo_vault'], ['zone_docking_hub', 'zone_observation_ring'], ['zone_tether_control', 'zone_observation_ring'], ['zone_cargo_vault', 'zone_observation_ring']],
  en: {
    title: 'Skyfall Silence',
    subtitle: 'Case LVL-05',
    setting: '2163. Skyhook One orbital elevator. A freighter captain dies in a vacuum lifeboat as an entire military cargo route vanishes.',
    scene: {
      description: 'The orbital elevator moves silently above the storm layer. Captain Jonah Vale is found trapped inside a depressurized lifeboat whose hatch remained locked from outside. In the same minute, an unregistered military container disappears from port control.',
      zones: {
        zone_docking_hub: { dom_id: 'area-docking-hub', label: 'Orbital Dock · Lifeboat', entry_requirement: null },
        zone_tether_control: { dom_id: 'area-tether-control', label: 'Tether Control Center', entry_requirement: 'hack_terminal' },
        zone_cargo_vault: { dom_id: 'area-cargo-vault', label: 'Zero-G Cargo Vault', entry_requirement: 'search_area' },
        zone_observation_ring: { dom_id: 'area-observation-ring', label: 'Observation Ring · Cameras', entry_requirement: 'check_cctv' },
      },
    },
    clue_dictionary: [
      { clue_id: 'g_01', keyword: 'Directed Depressurization', description: "The lifeboat valve opened through an external diagnostic command. Its mechanical safety remained intact, ruling out the captain's manual action.", visual_icon: '🛰️', weight: 'CRITICAL' },
      { clue_id: 'g_02', keyword: 'Forged Captain Order', description: "Port control records a cargo release signed by Jonah, but its latency does not match his neural key. It is a privileged copy.", visual_icon: '🪪', weight: 'CRITICAL' },
      { clue_id: 'g_03', keyword: 'Weapons-grade Isotope', description: 'Weapons-grade tritide remains at the missing container berth, while the manifest declares medical coolant.', visual_icon: '☢️', weight: 'HIGH' },
      { clue_id: 'g_04', keyword: "Rook's Control Access", description: "Cassian Rook's master account opened the diagnostic path two minutes before the death and disabled lifeboat alarm forwarding.", visual_icon: '🗝️', weight: 'CRITICAL' },
      { clue_id: 'g_05', keyword: "Yara's Calibration Record", description: 'Six independent sensors continuously place Yara at a public tether calibration during the incident.', visual_icon: '📐', weight: 'LOW' },
      { clue_id: 'g_06', keyword: "Ivo's Shadow Manifest", description: "Ivo's wrist terminal holds an off-chain manifest whose recipient code matches Rook's private company.", visual_icon: '📦', weight: 'HIGH' },
      { clue_id: 'g_07', keyword: 'Camera Parallax Ghost', description: 'The looped observation footage makes the starfield parallax jump every eighteen seconds, proving a short clip replaced live cameras.', visual_icon: '🎞️', weight: 'HIGH' },
      { clue_id: 'g_08', keyword: "Jonah's Emergency Beacon", description: "Before dying, Jonah transmitted: 'The supervisor is selling military car—do not trust the release record.'", visual_icon: '📡', weight: 'HIGH' },
      { clue_id: 'g_secret_99', keyword: 'Offline Container Ledger', description: 'A cargo maintenance node reveals six military-container transfers by Rook and Ivo, plus an elimination order for this run.', visual_icon: '🌌', weight: 'CRITICAL', unlock_turn: 8 },
    ],
    npcs: [
      { npc_id: 'npc_01', name: 'Cassian Rook', role: 'Orbital Elevator Director', public_persona: 'Calm and imposing; says he was coordinating storm-layer safety during the incident', personality: 'Uses regulations to suppress questions and reacts sharply to his private company and master-account access', avatar: '🧑‍✈️', initial_statement: 'Jonah violated lifeboat procedure. We lost a captain, but grief cannot become a foundation for reckless accusations.' },
      { npc_id: 'npc_02', name: 'Yara Sen', role: 'Tether Systems Engineer', public_persona: "Quiet and exacting; responsible for the elevator's most dangerous calibration", personality: 'Trusts sensor data and becomes forceful when politics overrides engineering', avatar: '👩‍🚀', initial_statement: "That lifeboat did not depressurize itself. Someone opened it through diagnostics. My calibration record proves I wasn't at the dock." },
      { npc_id: 'npc_03', name: 'Ivo Marek', role: 'Independent Orbital Courier', public_persona: 'Smooth and talkative; claims he transported only legal coolant', personality: 'Evades cargo provenance and starts bargaining when confronted with the manifest and isotope evidence', avatar: '🧑‍🚀', initial_statement: "I move sealed boxes to assigned berths. I don't have clearance—or interest—to know what is inside." },
    ],
    hidden_clues: [{ clue_id: 'g_secret_99', unlock_turn: 8, text: 'CARGO NODE ALERT: An off-chain transaction sector has been recovered...' }],
    zone_layout: {
      zone_docking_hub: { x: 50, y: 18, label: 'Orbital Dock', sublabel: 'Lifeboat Scene', icon: '🛰️', color: '#ff3860' },
      zone_tether_control: { x: 18, y: 60, label: 'Tether Control', sublabel: 'Master Access', icon: '🗼', color: '#00e5ff' },
      zone_cargo_vault: { x: 82, y: 60, label: 'Zero-G Cargo', sublabel: 'Missing Container', icon: '📦', color: '#a78bfa' },
      zone_observation_ring: { x: 50, y: 85, label: 'Observation Ring', sublabel: 'Camera Ghost', icon: '🔭', color: '#ffaa00' },
    },
  },
};
