// Global language context + translations
import React, { createContext, useContext, useState } from 'react';

export const LANG = {
  zh: {
    systemVersion: 'TERMINAL DETECTIVE · SYSTEM v2.1.57',
    online: '● 在线', secure: '◈ 安全', ready: '⚡ 就绪',
    caseBadge: '◈ 案件档案 · LVL_01 · OMEGA 难度',
    subtitle: '霓虹血迹 · NEON BLOOD · 2157',
    zones: '调查区域', suspects: '嫌疑人', clues: '隐藏线索', difficulty: '难度评级',
    startBtn: '▶ 开始调查',
    startHint: '请先配置您的探员团队',
    bottomBar: '多智能体调查平台 · 神经推理引擎驱动',
    features: [
      { icon: '🧠', title: '神经推理引擎', desc: 'ReAct 多阶段思维链，动态适应每一条证据链' },
      { icon: '🕵️', title: '多智能体编队', desc: '三名专属探员协同部署，技能互补触发连击增益' },
      { icon: '🗺', title: '动态案件流程图', desc: '可视化调查路径，拖拽节点优化优先级策略' },
      { icon: '⚡', title: '实时协同特效', desc: '粒子数据流 · AP 奖励连击 · 三重协同爆发' },
    ],
    minimap: '◈ 小地图', collapse: '▲ 收起', expand: '▼ 展开',
    currentPos: '当前位置', investigated: '已调查', unexplored: '未探索',
    clueLabel: '线索', zonesLabel: '区域', apLabel: 'AP',
    plotSummary: '◎ 情节摘要', clueDetails: '◎ 线索详情', noClues: '暂无线索',
    langBtn: 'EN',
    // CaseSelect
    caseArchiveTitle: '案件档案库',
    caseArchiveSubtitle: '选择一个案件开始调查',
    backToLobby: '← 返回大厅',
    selectInvestigation: 'SELECT INVESTIGATION',
    clueStat: '线索', npcStat: 'NPC', zoneStat: '区域',
    startCase: '▶ 开始调查', loadingCase: '▶ 正在载入...',
    caseArchiveFooter: 'TERMINAL DETECTIVE · 案件档案 · 5个案件可选',
    // InvestigationTerminal HUD
    hudPhase: '阶段', hudHp: 'HP', hudAp: 'AP', hudClues: '线索', hudConfusion: '混乱',
    btnMap: '🗺 地图', btnBoard: '🕸 证物板', btnLog: '📓 日志', btnReport: '📋 报告', btnEnd: '⏹ 结束',
    reportTitle: '◈ 案件报告 — 提交推理至法官：',
    reportPlaceholder: '陈述您的结论：谁是凶手？如何作案？为何作案？有何证据支撑？',
    reportSubmit: '▶ 提交至法官',
    reportCancel: '取消',
    evidenceLocker: '◈ 证物库',
    noEvidence: '尚无证据。\n开始调查。',
    confusionLabel: '混乱',
    lobbyBtn: '← 大厅',
    interrogating: '审讯中',
    sendBtn: '发送',
    abortBtn: '⬛ 中止',
    executeCycle: '▶ 执行循环',
    systemScan: '◈ 系统扫描',
    location: '位置',
    contacts: '接触人',
    evidenceStat: '证据',
    turnLabel: '回合',
    observationPhase: '观察阶段',
    neuralProcessing: '◈ 进入神经处理模式...',
    actionSynthesis: '◈ 行动合成...',
    resolvingAction: '⏳ 处理行动...',
    logicConflict: '⚠ 逻辑冲突检测：矩阵中存在相互矛盾的证据。混乱 +15。',
    encryptedMessage: '🔐 收到加密信息：',
    newEvidenceSecured: '📦 新证据已保护：',
    systemCrashed: '🛑 代理行动被建筑师中止',
    apDepleted: '⚠ 严重警告：行动点已耗尽，请立即提交案件报告。',
    keyDecisionNode: '⏸ 关键决策节点 — AI 自动执行已挂起，等待架构师指令',
    architectConfirm: '🎯 架构师指令确认：',
    adversarialEvent: '🎭 [对抗事件]',
    newEvidenceFound: '🔍 已保全新证据：',
    caseSolved: '🎉 案件告破 — 架构师胜利！',
    judgeVerdict: '📋 法官裁定',
    reportRejected: '⛔ 报告被驳回',
    judgeLabel: '📋 法官：',
    agentRebooted: '🔄 探员已重启：混乱值归零，扣除行动点。',
    npcEnters: '进入房间',
    narrativeCollapse: '🎭 叙事崩塌：',
    apPenalty: '💀 行动点惩罚：',
    systemError: '❌ 系统错误：',
    reasonConfusion: '混乱值超过 40',
    reasonClues: '已解锁线索超过 4 条',
    reasonAP: '剩余 AP 不足 5',
    riskSteady: '稳健', riskAggressive: '激进', riskHigh: '高风险',
    riskSteadyDesc: 'AI 综合当前线索链得出的最优推进方案',
    riskAggressiveDesc: '主动出击施压，可能快速突破，也可能推高混乱值',
    riskHighDesc: '高收益高风险，失败可能触发对抗事件',
    insightBreak: '⚡ 推理突破！',
    logicInvalid: '✕ 逻辑不成立：',
    confusionPlus1: '（混乱值 +1）',
    linkFailed: '❌ 推理验证失败：',
    caseClosedTag: '✓ 案件结案',
    reportRejectedTag: '✗ 报告驳回',
  },
  en: {
    systemVersion: 'TERMINAL DETECTIVE · SYSTEM v2.1.57',
    online: '● ONLINE', secure: '◈ SECURE', ready: '⚡ READY',
    caseBadge: '◈ CASE FILE · LVL_01 · OMEGA DIFFICULTY',
    subtitle: 'NEON BLOOD · 2157',
    zones: 'ZONES', suspects: 'SUSPECTS', clues: 'CLUES', difficulty: 'DIFFICULTY',
    startBtn: '▶ START INVESTIGATION',
    startHint: 'CONFIGURE YOUR AGENT TEAM FIRST',
    bottomBar: 'MULTI·AGENT·INVESTIGATIVE·PLATFORM · POWERED BY NEURAL REASONING ENGINE',
    features: [
      { icon: '🧠', title: 'Neural Reasoning Engine', desc: 'ReAct multi-step thought chains, adapting dynamically to every evidence trail' },
      { icon: '🕵️', title: 'Multi-Agent Squad', desc: 'Three specialist agents deploy in synergy, triggering combo bonuses' },
      { icon: '🗺', title: 'Dynamic Case Flow Map', desc: 'Visualize investigation paths, drag nodes to optimize priority strategy' },
      { icon: '⚡', title: 'Real-Time Synergy FX', desc: 'Particle data streams · AP reward combos · Triple-agent burst' },
    ],
    minimap: '◈ MINI MAP', collapse: '▲ HIDE', expand: '▼ SHOW',
    currentPos: 'Current', investigated: 'Visited', unexplored: 'Unknown',
    clueLabel: 'Clue', zonesLabel: 'Zones', apLabel: 'AP',
    plotSummary: '◎ PLOT SUMMARY', clueDetails: '◎ CLUE LOG', noClues: 'No clues yet',
    langBtn: '中',
    // CaseSelect
    caseArchiveTitle: 'CASE ARCHIVE',
    caseArchiveSubtitle: 'Select a case to begin your investigation',
    backToLobby: '← BACK TO LOBBY',
    selectInvestigation: 'SELECT INVESTIGATION',
    clueStat: 'Clues', npcStat: 'NPCs', zoneStat: 'Zones',
    startCase: '▶ START CASE', loadingCase: '▶ LOADING...',
    caseArchiveFooter: 'TERMINAL DETECTIVE · CASE ARCHIVE · 5 INVESTIGATIONS AVAILABLE',
    // InvestigationTerminal HUD
    hudPhase: 'PHASE', hudHp: 'HP', hudAp: 'AP', hudClues: 'CLUES', hudConfusion: 'CONFUSION',
    btnMap: '🗺 MAP', btnBoard: '🕸 BOARD', btnLog: '📓 LOG', btnReport: '📋 REPORT', btnEnd: '⏹ END',
    reportTitle: '◈ CASE REPORT — Submit your reasoning to the Judge:',
    reportPlaceholder: 'State your conclusion: Who did it? How? Why? What evidence supports your case?',
    reportSubmit: '▶ SUBMIT TO JUDGE',
    reportCancel: 'CANCEL',
    evidenceLocker: '◈ EVIDENCE LOCKER',
    noEvidence: 'No evidence secured.\nBegin investigation.',
    confusionLabel: 'CONFUSION',
    lobbyBtn: '← LOBBY',
    interrogating: 'INTERROGATING',
    sendBtn: 'SEND',
    abortBtn: '⬛ ABORT',
    executeCycle: '▶ EXECUTE CYCLE',
    systemScan: '◈ SYSTEM SCAN',
    location: 'Location',
    contacts: 'Contacts',
    evidenceStat: 'Evidence',
    turnLabel: 'TURN',
    observationPhase: 'OBSERVATION PHASE',
    neuralProcessing: '◈ ENTERING NEURAL PROCESSING MODE...',
    actionSynthesis: '◈ ACTION SYNTHESIS...',
    resolvingAction: '⏳ Resolving action...',
    logicConflict: '⚠ LOGIC CONFLICT DETECTED: Contradictory evidence in matrix. Confusion +15.',
    encryptedMessage: '🔐 ENCRYPTED MESSAGE RECEIVED:',
    newEvidenceSecured: '📦 New evidence secured:',
    systemCrashed: '🛑 AGENT ACTION ABORTED BY ARCHITECT',
    apDepleted: '⚠ CRITICAL: Action Points depleted. File your report now.',
    keyDecisionNode: '⏸ KEY DECISION NODE — Autonomous execution suspended, awaiting Architect orders',
    architectConfirm: '🎯 ARCHITECT ORDER CONFIRMED: ',
    adversarialEvent: '🎭 [ADVERSARIAL EVENT]',
    newEvidenceFound: '🔍 NEW EVIDENCE SECURED: ',
    caseSolved: '🎉 CASE SOLVED — ARCHITECT VICTORIOUS!',
    judgeVerdict: '📋 Judge verdict',
    reportRejected: '⛔ REPORT REJECTED',
    judgeLabel: '📋 Judge: ',
    agentRebooted: '🔄 AGENT REBOOTED. Confusion reset. AP penalty applied.',
    npcEnters: 'enters the room',
    narrativeCollapse: '🎭 NARRATIVE COLLAPSE: ',
    apPenalty: '💀 AP penalty: ',
    systemError: '❌ SYSTEM ERROR: ',
    reasonConfusion: 'Confusion above 40',
    reasonClues: 'More than 4 clues unlocked',
    reasonAP: 'Less than 5 AP remaining',
    riskSteady: 'STEADY', riskAggressive: 'AGGRESSIVE', riskHigh: 'HIGH RISK',
    riskSteadyDesc: 'The optimal next step derived from the current evidence chain',
    riskAggressiveDesc: 'Apply pressure directly — fast breakthrough, or rising confusion',
    riskHighDesc: 'High reward, high risk — failure may trigger an adversarial event',
    insightBreak: '⚡ DEDUCTION BREAKTHROUGH! ',
    logicInvalid: '✕ LOGIC INVALID: ',
    confusionPlus1: ' (Confusion +1)',
    linkFailed: '❌ Deduction check failed: ',
    caseClosedTag: '✓ CASE CLOSED',
    reportRejectedTag: '✗ REPORT REJECTED',
  },
};

const LangContext = createContext({ lang: 'zh', t: LANG.zh, setLang: (_value) => {} });

const LANG_KEY = 'td_lang_v1';

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      const saved = localStorage.getItem(LANG_KEY);
      return saved === 'en' || saved === 'zh' ? saved : 'zh';
    } catch { return 'zh'; }
  });
  const setLang = (next) => {
    const value = typeof next === 'function' ? next(lang) : next;
    try { localStorage.setItem(LANG_KEY, value); } catch { /* ignore */ }
    setLangState(value);
  };
  const t = LANG[lang];
  return <LangContext.Provider value={{ lang, t, setLang }}>{children}</LangContext.Provider>;
}

export function useLang() { return useContext(LangContext); }
